global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Shared.Database.Data;
global using Shared.Database.Data.Entities;
global using Shared.Database.Data.EntityConfigs;
